export const NOTIFICATION_LIST_REQUEST = 'NOTIFICATION_LIST_REQUEST'
export const NOTIFICATION_LIST_SUCCESS = 'NOTIFICATION_LIST_SUCCESS'
export const NOTIFICATION_LIST_FAIL = 'NOTIFICATION_LIST_FAIL'


export const NOTIFICATION_DETAILS_REQUEST = 'NOTIFICATION_DETAILS_REQUEST'
export const NOTIFICATION_DETAILS_SUCCESS = 'NOTIFICATION_DETAILS_SUCCESS'
export const NOTIFICATION_DETAILS_FAIL = 'NOTIFICATION_DETAILS_FAIL'


export const NOTIFICATION_DELETE_REQUEST = 'NOTIFICATION_DELETE_REQUEST'
export const NOTIFICATION_DELETE_SUCCESS = 'NOTIFICATION_DELETE_SUCCESS'
export const NOTIFICATION_DELETE_FAIL = 'NOTIFICATION_DELETE_FAIL'


export const NOTIFICATION_CREATE_REQUEST = 'NOTIFICATION_CREATE_REQUEST'
export const NOTIFICATION_CREATE_SUCCESS = 'NOTIFICATION_CREATE_SUCCESS'
export const NOTIFICATION_CREATE_FAIL = 'NOTIFICATION_CREATE_FAIL'
export const NOTIFICATION_CREATE_RESET = 'NOTIFICATION_CREATE_RESET'


export const NOTIFICATION_UPDATE_REQUEST = 'NOTIFICATION_UPDATE_REQUEST'
export const NOTIFICATION_UPDATE_SUCCESS = 'NOTIFICATION_UPDATE_SUCCESS'
export const NOTIFICATION_UPDATE_FAIL = 'NOTIFICATION_UPDATE_FAIL'
export const NOTIFICATION_UPDATE_RESET = 'NOTIFICATION_UPDATE_RESET'
