# Generated by Django 3.1.4 on 2022-06-23 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20220623_2224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='notif_link',
            new_name='link',
        ),
    ]
